//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DyMenu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DyMenuEntities : DbContext
    {
        public DyMenuEntities()
            : base("name=DyMenuEntities")
        {
        }
        public virtual DbSet<MainMenu> MainMenus { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        modelBuilder.Entity<MainMenu>().HasMany(e => e.SubMenus)
               .WithRequired(e => e.MainMenu).WillCascadeOnDelete(false);

        }


    }
}
